services:
  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: training
    ports: 
      - "5432:5432"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data: 
